import{i as d,S as b,a as w}from"./assets/vendor-c493984e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const L="44082104-13032bddabedf7f071f678933",q="https://pixabay.com/api/";async function S(t){const r=`${q}?key=${L}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true`,o=await fetch(r);if(!o.ok)throw new Error("Network response was not ok");return await o.json()}let c,l=1,i="";const $=15;async function m(t){try{return(await w.get("https://pixabay.com/api/",{params:{key:"44082104-13032bddabedf7f071f678933",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:l,per_page:$}})).data.hits}catch(r){return console.error("Error fetching images:",r),[]}}function u(t){const r=document.querySelector(".gallery");if(t.length===0){d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const o=t.map(({webformatURL:s="",largeImageURL:e="",tags:n="",likes:a=0,views:y=0,comments:g=0,downloads:h=0})=>`
    <a class="gallery__item" href="${e}" data-caption="${n}">
      <img src="${s}" alt="${n}" loading="lazy" />
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${a}</p>
        <p class="info-item"><b>Views:</b> ${y}</p>
        <p class="info-item"><b>Comments:</b> ${g}</p>
        <p class="info-item"><b>Downloads:</b> ${h}</p>
      </div>
    </a>
  `).join("");r.insertAdjacentHTML("beforeend",o),c?c.refresh():c=new b(".gallery a")}async function v(){l+=1;const t=await m(i);u(t)}function f(){document.querySelector(".loader").classList.remove("hidden")}function p(){document.querySelector(".loader").classList.add("hidden")}async function E(t){if(t.preventDefault(),i=document.querySelector(".search-form input").value.trim(),!i){d.warning({title:"Warning",message:"Please enter a search query!"});return}l=1,document.querySelector(".gallery").innerHTML="",f();const o=await m(i);p(),u(o)}document.querySelector(".search-form").addEventListener("submit",E);document.querySelector(".load-more-btn").addEventListener("click",v);document.querySelector(".search-form").addEventListener("submit",async t=>{t.preventDefault();const r=t.target.elements.searchQuery.value.trim();if(!r){iziToast.warning({title:"Warning",message:"Please enter a search query!"});return}f();try{const o=await S(r);u(o.hits)}catch(o){iziToast.error({title:"Error",message:`Something went wrong: ${o.message}`})}finally{p()}});window.addEventListener("scroll",()=>{const{scrollTop:t,scrollHeight:r,clientHeight:o}=document.documentElement;t+o>=r-100?document.querySelector(".load-more-btn").style.display="block":document.querySelector(".load-more-btn").style.display="none"});
//# sourceMappingURL=commonHelpers.js.map
